/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp com.qt.example.dbus.xml -a test_adaptor
 *
 * qdbusxml2cpp is Copyright (C) 2020 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "test_adaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DbusAdaptor
 */

DbusAdaptor::DbusAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DbusAdaptor::~DbusAdaptor()
{
    // destructor
}

bool DbusAdaptor::inhibited() const
{
    // get the value of property Inhibited
    return qvariant_cast< bool >(parent()->property("Inhibited"));
}

QVariantMap DbusAdaptor::getMap(const QVariantList &list)
{
    // handle method call com.qt.example.dbus.getMap
    QVariantMap out0;
    QMetaObject::invokeMethod(parent(), "getMap", Q_RETURN_ARG(QVariantMap, out0), Q_ARG(QVariantList, list));
    return out0;
}

QString DbusAdaptor::printStr(const QString &str)
{
    // handle method call com.qt.example.dbus.printStr
    QString out0;
    QMetaObject::invokeMethod(parent(), "printStr", Q_RETURN_ARG(QString, out0), Q_ARG(QString, str));
    return out0;
}

